// Inject a task-grouped table of contents into packages/runtime/API.md.
//
// typedoc's default grouping is by TypeScript kind (Classes,
// Interfaces, Type Aliases, Variables, Functions). For a public
// reference that's mechanical, not navigable. This post-processor
// keeps the per-kind bodies typedoc emits and prepends a hand-curated
// TOC that buckets symbols by "what is the reader trying to do?".
//
// The mapping below is the single source of truth for those buckets.
// When you add a new public export to packages/runtime/src/index.ts,
// add the symbol here too (or it lands in "Other"). Run is:
//
//   pnpm build:docs   (typedoc → this script)
//
// The script validates that every symbol it references is a real H3
// in the generated API.md and that no H3 is left uncategorised, so
// drift between source exports and the TOC fails the build instead
// of silently producing broken anchors.

import { readFileSync, writeFileSync } from "node:fs";

// Optional path arg so the api-md-drift test can point at a tmpdir
// copy without clobbering the committed file. Defaults to the path
// `pnpm run build:docs` uses.
const API_PATH = process.argv[2] ?? "packages/runtime/API.md";

// Categories ordered top-to-bottom in the rendered TOC. Each value is
// the list of H3 headers (i.e. symbol names) typedoc emits for that
// category. Plain function/type names map 1:1 to typedoc's H3 text.
const TOC = {
  "Boot a VM": [
    "boot",
    "BootOptions",
    "attach",
    "AttachOptions",
    "bootPty",
    "PtyBootOptions",
    "PtyVmHandle",
    "VmHandle",
    "ImageConfig",
    "autoSizeMemoryMib",
    "resolveVmmBinary",
    "warmImageConfigCache",
    "measureFirstByte",
  ],
  "Run code in a VM": [
    "VsockExec",
    "VsockExecOptions",
    "VsockExecResult",
    "VsockExecPtyHandle",
    "VsockExecPtyOptions",
    "VsockExecPtyResult",
  ],
  "Snapshot, restore, fork": [
    "restore",
    "RestoreOptions",
    "ForkOptions",
    "SnapshotOptions",
    "SnapshotResult",
    "SnapshotFileIdentity",
    "SnapshotMeta",
    "VmstateBackend",
    "VmstateSnapshotMeta",
    "SnapshotEngine",
    "bootSnapshotPath",
    "writeBootSnapshot",
    "detachedLogRoot",
  ],
  "Advanced Linux facility probes": [
    "AdvancedLinuxFacilityProbeClassification",
    "AdvancedLinuxFacilityProbeFacility",
    "AdvancedLinuxFacilityProbeInput",
    "AdvancedLinuxFacilityProbeRefusalCode",
    "AdvancedLinuxFacilityProbeRow",
    "AdvancedLinuxFacilityProbeStateModel",
    "AdvancedLinuxFacilityProbeSummary",
    "ADVANCED_LINUX_FACILITY_PROBE_KIND",
    "advancedLinuxFacilityProbeClassifications",
    "advancedLinuxFacilityProbeFacilities",
    "advancedLinuxFacilityProbeRefusalCodes",
    "buildAdvancedLinuxFacilityProbeRow",
    "summarizeAdvancedLinuxFacilityProbeRows",
    "validateAdvancedLinuxFacilityProbeRows",
  ],
  "Runtime confidence profiles": [
    "RuntimeConfidenceArch",
    "RuntimeConfidenceClassification",
    "RuntimeConfidenceProfileInput",
    "RuntimeConfidenceProfileRow",
    "RuntimeConfidenceProfileSummary",
    "RuntimeConfidenceRefusalCode",
    "RuntimeConfidenceRuntime",
    "RuntimeConfidenceStateModel",
    "RUNTIME_CONFIDENCE_PROFILE_KIND",
    "runtimeConfidenceClassifications",
    "runtimeConfidenceRefusalCodes",
    "buildRuntimeConfidenceProfileMatrix",
    "buildRuntimeConfidenceProfileRow",
    "runtimeConfidenceProfileFixtures",
    "summarizeRuntimeConfidenceProfiles",
    "validateRuntimeConfidenceProfiles",
  ],
  "Portable snapshot + guest CRIU composition": [
    "PortableSnapshotGuestCriuCompositionInput",
    "PortableSnapshotGuestCriuCompositionRefusalCode",
    "PortableSnapshotGuestCriuCompositionRow",
    "PortableSnapshotGuestCriuCompositionState",
    "PortableSnapshotGuestCriuCompositionSummary",
    "PortableSnapshotGuestCriuMachinenStateModel",
    "PORTABLE_SNAPSHOT_GUEST_CRIU_COMPOSITION_KIND",
    "portableSnapshotGuestCriuCompositionRefusalCodes",
    "buildPortableSnapshotGuestCriuCompositionRow",
    "summarizePortableSnapshotGuestCriuCompositionRows",
    "validatePortableSnapshotGuestCriuCompositionRows",
  ],
  "Guest CRIU substrate": [
    "GuestCriuSubstrateInput",
    "GuestCriuSubstrateProfile",
    "GuestCriuSubstrateRefusalCode",
    "GuestCriuSubstrateRow",
    "GuestCriuSubstrateState",
    "GuestCriuSubstrateSummary",
    "GUEST_CRIU_SUBSTRATE_KIND",
    "guestCriuSubstrateRefusalCodes",
    "buildGuestCriuSubstrateRow",
    "summarizeGuestCriuSubstrateRows",
    "validateGuestCriuSubstrateRows",
  ],
  "Stateful database restore": [
    "StatefulDatabaseRestoreArch",
    "StatefulDatabaseRestoreDatabase",
    "StatefulDatabaseRestoreInput",
    "StatefulDatabaseRestoreRefusalCode",
    "StatefulDatabaseRestoreState",
    "StatefulDatabaseRestoreStateModel",
    "StatefulDatabaseRestoreSummary",
    "STATEFUL_DATABASE_RESTORE_KIND",
    "statefulDatabaseRestoreRefusalCodes",
    "buildStatefulDatabaseRestoreSummary",
    "postgresLogicalRestoreInput",
    "sqliteRollbackJournalRestoreInput",
    "sqliteWalCheckpointRestoreInput",
  ],
  "Opposite-ISA VM execution": [
    "OppositeIsaVmExecutionArch",
    "OppositeIsaVmExecutionEvidence",
    "OppositeIsaVmExecutionProviderRoute",
    "OppositeIsaVmExecutionRefusalCode",
    "OppositeIsaVmExecutionState",
    "OppositeIsaVmExecutionSummary",
    "OPPOSITE_ISA_VM_EXECUTION_KIND",
    "oppositeIsaVmExecutionRefusalCodes",
    "buildOppositeIsaVmExecutionSummary",
    "classifyOppositeIsaProviderRoute",
    "hostArchitectureFromNode",
    "normalizeGuestMachine",
    "oppositeGuestArchitecture",
  ],
  "Product claim registry": [
    "ProductClaimProofProfileInput",
    "ProductClaimEntry",
    "ProductClaimRegistry",
    "ProductClaimRegistrySummary",
    "ProductClaimRegistryFilter",
    "ProductClaimStatus",
    "ProductClaimFamily",
    "PRODUCT_CLAIM_REGISTRY_FORMAT_VERSION",
    "productClaimStatuses",
    "productClaimFamilies",
    "PRODUCT_CLAIM_PROOF_ONLY_REFUSAL_CODE",
    "buildProductClaimRegistry",
    "productClaimEntryFromProofProfile",
    "summarizeProductClaimRegistry",
    "filterProductClaimRegistry",
    "productClaimRefusalSummary",
  ],
  "Product portable PostgreSQL": [
    "ProductPortablePostgresError",
    "ProductPortablePostgresClaimClassification",
    "ProductPortablePostgresCaptureInput",
    "ProductPortablePostgresDescriptor",
    "ProductPortablePostgresRefusal",
    "ProductPortablePostgresRestoreInput",
    "ProductPortablePostgresRestoreSummary",
    "ProductPortablePostgresArchitecture",
    "ProductPortableSupportLevel",
    "ProductPortablePostgresRefusalCode",
    "ProductPortablePostgresCaptureResult",
    "PRODUCT_PORTABLE_POSTGRES_FORMAT_VERSION",
    "PRODUCT_PORTABLE_POSTGRES_MANIFEST",
    "PRODUCT_PORTABLE_POSTGRES_REFUSAL",
    "PRODUCT_PORTABLE_POSTGRES_RESTORE_SUMMARY",
    "PRODUCT_PORTABLE_POSTGRES_DUMP",
    "productPortablePostgresArchitectures",
    "productPortablePostgresSupportLevels",
    "productPortablePostgresRefusalCodes",
    "createProductPortablePostgresSnapshot",
    "restoreProductPortablePostgresSnapshot",
    "isProductPortablePostgresBundle",
    "productPortablePostgresFileSha256",
  ],
  "Native process images": [
    "NativeProcessImageValidationError",
    "NativeProcessImageRefusal",
    "NativeProcessImageRefusals",
    "NativeProcessImageManifest",
    "NativeMemoryMapping",
    "NativeProcessImageMappings",
    "NativeArm64Registers",
    "NativeAmd64Registers",
    "NativeSimdFpuLiveSubset",
    "NativeSimdFpuState",
    "NativeThreadState",
    "NativeProcessImageThreads",
    "NativeProcessResource",
    "NativeProcessImageResources",
    "NativeCodeLocationMapping",
    "NativeThreadTranslation",
    "NativeMemoryRelocation",
    "NativeProcessImageTranslation",
    "NativeProcessImageDocuments",
    "NativeProcessImageDocumentInput",
    "NativeProcessImageArchitecture",
    "NativeProcessImageRefusalCode",
    "NativeMemoryMappingKind",
    "NativeRegisterState",
    "NativeProcessResourceKind",
    "NativeProcessImageJsonSchema",
    "NATIVE_PROCESS_IMAGE_FORMAT_VERSION",
    "NATIVE_PROCESS_IMAGE_FILES",
    "nativeProcessImageArchitectures",
    "nativeProcessImageRefusalCodes",
    "nativeProcessImageSchemas",
    "isNativeProcessImageBundle",
    "validateNativeProcessImageBundle",
    "validateNativeProcessImageDocuments",
    "assertNativeProcessImageDocuments",
    "PortableMachineSnapshotArchitecture",
    "PortableMachineSnapshotRefusalCode",
    "PortableMachineSnapshotRefusal",
    "PortableMachineSnapshotRefusals",
    "PortableMachineSnapshotManifest",
    "PortableMachineSnapshotDocuments",
    "PORTABLE_MACHINE_SNAPSHOT_FORMAT_VERSION",
    "PORTABLE_MACHINE_SNAPSHOT_FILES",
    "portableMachineSnapshotArchitectures",
    "portableMachineSnapshotRefusalCodes",
    "portableMachineSnapshotManifestSchema",
    "PortableMachineSnapshotValidationError",
    "crossIsaVmstateRestoreRefusal",
    "buildPortableMachineSnapshotManifestFromNativeProcessImage",
    "isPortableMachineSnapshotBundle",
    "validatePortableMachineSnapshotBundle",
    "validatePortableMachineSnapshotManifest",
    "TargetGuestRestoreLoaderValidationError",
    "TargetGuestRestoreLoaderRefusalCode",
    "TargetGuestEpollWatchRecipe",
    "TargetGuestRestoreResourceRecipe",
    "TargetGuestRestoreResumeMode",
    "TargetGuestResumeRegisterName",
    "TargetGuestResumeRegisters",
    "TargetGuestNativeRestoreStep",
    "TargetGuestRestoreContinuationDescriptor",
    "TargetGuestRestoreDescriptor",
    "TargetGuestTranslatedFrameDescriptor",
    "TargetGuestTranslatedFrameRegister",
    "TargetGuestTranslatedFrameRegisterName",
    "TargetGuestTranslatedFrameSlot",
    "TargetGuestActiveSyscallRestorePlan",
    "TargetGuestActiveSyscallRestoreStep",
    "TargetGuestExecutableMappingStep",
    "TargetGuestExecutableMaterializationPlan",
    "TargetGuestMemoryMaterializationKind",
    "TargetGuestMemoryMaterializationEntry",
    "TargetGuestCopyCapturedBytesEntry",
    "TargetGuestRecreateGuardEntry",
    "TargetGuestMemoryMaterializationRequest",
    "TargetGuestMemoryMaterializationResult",
    "TargetGuestPrivateMemoryRestorePlan",
    "TargetGuestPrivateMemoryRestoreStep",
    "TargetGuestProcessContextRestoreMode",
    "TargetGuestProcessContextRestoreOptions",
    "TargetGuestProcessContextRestorePlan",
    "TargetGuestProcessContextRestoreStep",
    "TargetGuestSignalRestorePlan",
    "TargetGuestSignalRestoreStep",
    "TargetGuestTwoThreadBinding",
    "TargetGuestTwoThreadRestorePlan",
    "TargetNativeConsumptionEvent",
    "TargetNativeConsumptionEvents",
    "TargetNativeConsumptionStatus",
    "TargetGuestTwoThreadSpawnStep",
    "PortableMachineTargetRestoreDescriptorRequest",
    "PortableMachineTargetRestoreDescriptorPlan",
    "PortableMachineTargetRestoreObservation",
    "PortableMachineVmRestoreProofState",
    "PortableMachineTargetContinuationKind",
    "PortableMachineTargetFrameRestoreResult",
    "PortableMachineTargetRegisterRestoreResult",
    "PortableMachineTargetRflagsRestoreResult",
    "PortableMachineTargetTlsRestoreResult",
    "PortableMachineTargetThreadRestoreResult",
    "PortableMachineTargetResourceStatus",
    "PortableMachineTargetResumePathResult",
    "PortableMachineTargetReturnChainResult",
    "PortableMachineTargetNativePlanConsumptionResult",
    "PortableMachineTargetStateConsumptionResult",
    "PortableMachineTargetVerifierResult",
    "PortableMachineVmRestoreProofRequest",
    "PortableMachineVmRestoreProofPlan",
    "PortableMachineVmRestoreTargetResult",
    "TARGET_GUEST_RESTORE_DESCRIPTOR_KIND",
    "serializeTargetGuestRestoreDescriptor",
    "parseTargetGuestRestoreDescriptor",
    "validateTargetGuestRestoreDescriptor",
    "planTargetGuestActiveSyscallRestore",
    "planTargetGuestExecutableMaterialization",
    "planTargetGuestMemoryMaterialization",
    "planTargetGuestPrivateMemoryRestore",
    "planTargetGuestProcessContextRestore",
    "planTargetGuestSignalRestore",
    "planTargetGuestTwoThreadRestore",
    "parseTargetNativeConsumptionEvents",
    "targetNativeConsumptionFields",
    "targetNativeConsumptionPassed",
    "planPortableMachineTargetRestoreDescriptor",
    "planPortableMachineVmRestoreProof",
    "completePortableMachineVmRestoreProof",
    "buildNativeActualResumeTrampolineArgs",
    "buildTargetGuestRestoreLoaderArgv",
    "NativeRegisterTranslationRequest",
    "NativeContinuationTarget",
    "NativeRegisterTranslationResult",
    "NativeTlsThreadPointerRegister",
    "NativeTlsAmd64SegmentBases",
    "NativeThreadRestorePlan",
    "NativeThreadRestorePlanRequest",
    "NativeControlledTwoThreadRestorePlan",
    "NativeControlledTwoThreadRestorePlanRequest",
    "NativeSignalBlockedMaskPolicy",
    "NativeSignalRestorePolicyRequest",
    "NativeSignalRestorePolicyResult",
    "NativeSimdFpuLiveSubsetPolicy",
    "NativeSimdFpuRestorePolicyResult",
    "NativeThreadTlsPolicyRequest",
    "NativeTlsSegmentBaseHandoffRequest",
    "NativeTlsSegmentBaseHandoffResult",
    "NativeTlsTargetAccessPolicy",
    "translateNativeRegisterState",
    "planNativeThreadRestoreBoundary",
    "planNativeControlledTwoThreadRestoreBoundary",
    "planNativeSignalRestorePolicy",
    "safeSignalRestoreRefusal",
    "NATIVE_SIMD_FPU_LIVE_SUBSET_POLICY",
    "planNativeSimdFpuLiveSubsetPolicy",
    "planNativeSimdFpuRestorePolicy",
    "safeSimdFpuRefusal",
    "planNativeTlsSegmentBaseHandoff",
    "safeTlsSegmentBaseRefusal",
    "NativeActiveSyscallClass",
    "NativeSleepTimerSyscallPolicy",
    "NativePollTimeoutSyscallPolicy",
    "NativePollTimeoutFdPolicy",
    "NativeFdReadPolicy",
    "NativeFdReadResourcePolicy",
    "NativeFdWritePolicy",
    "NativeFdWriteResourcePolicy",
    "NativePingSocketRecvmsgPolicy",
    "NativeActiveSyscallPolicyOptions",
    "NativeSleepTimerDuration",
    "NativeModeledSleepTimerRemainingTime",
    "NativeModeledSleepTimerState",
    "NativeModeledPpollTimeoutRemainingTime",
    "NativeModeledPpollTargetResource",
    "NativeModeledPpollFdState",
    "NativeModeledPpollTimeoutState",
    "NativeModeledFdReadTargetResource",
    "NativeModeledFdReadTimerRemainingTime",
    "NativeModeledFdReadState",
    "NativeModeledFdWriteTargetResource",
    "NativeModeledFdWriteState",
    "NativeModeledPingSocketRecvmsgState",
    "NativeSleepTimerModelResult",
    "NativePpollTimeoutModelResult",
    "NativeFdReadModelResult",
    "NativeFdWriteModelResult",
    "NativePingSocketRecvmsgModelResult",
    "NativeActiveSleepTimerContinuation",
    "NativeActivePpollTimeoutContinuation",
    "NativeActiveFdReadContinuation",
    "NativeActiveFdWriteContinuation",
    "NativeActivePingSocketRecvmsgContinuation",
    "NativeActiveSyscallContinuation",
    "NativeActiveSyscallClassification",
    "NativeActiveSyscallClassificationResult",
    "modelNativeSleepTimerState",
    "modelNativePpollTimeoutState",
    "modelNativeFdReadState",
    "modelNativeFdWriteState",
    "modelNativePingSocketRecvmsgState",
    "classifyNativeThreadSyscall",
    "classifyNativeActiveSyscalls",
    "NativeCodeModule",
    "NativeCodeSymbol",
    "NativeCodeMapRequest",
    "NativeCodeMapResult",
    "buildNativeCodeMap",
    "NativeRealUtilityExecutableRange",
    "NativeRealUtilitySourceModule",
    "NativeRealUtilityTargetModule",
    "NativeRealUtilityModuleExpectation",
    "NativeRealUtilityTargetContinuationKind",
    "NativeRealUtilityTargetSemanticContinuation",
    "NativeRealUtilityContinuationStrategy",
    "NativeRealUtilitySemanticContinuationSelection",
    "NativeRealUtilitySyntheticContinuationSelection",
    "NativeRealUtilityDeferredActiveSyscallLanding",
    "NativeRealUtilityResolvedLocation",
    "NativeRealUtilityCodeLocationRequest",
    "NativeRealUtilityCodeLocationResult",
    "inventoryNativeSourceCodeModules",
    "resolveNativeRealUtilityCodeLocations",
    "NativeRealUtilityContinuationBoundary",
    "NativeRealUtilityContinuationRequest",
    "NativeRealUtilityContinuationPlan",
    "planNativeRealUtilityContinuationAttempt",
    "NativeActualRealUtilityContinuationBoundary",
    "NativeActualRealUtilityContinuationRequest",
    "NativeActualRealUtilityContinuationPlan",
    "planNativeActualRealUtilityContinuationAttempt",
    "NativeActualTargetModuleInventoryRequest",
    "NativeActualTargetModuleInventoryResult",
    "inventoryNativeActualTargetModules",
    "NativeTargetModuleByteMaterializationRequest",
    "NativeTargetModuleByteMaterialization",
    "NativeTargetModuleByteMaterializationResult",
    "materializeNativeTargetModuleBytes",
    "NativeSyntheticContinuationTargetArch",
    "NativeSyntheticContinuationByteSource",
    "NativeSyntheticContinuationByteEncoding",
    "NativeSyntheticContinuationSyscallAbi",
    "NativeSyntheticContinuationRegisterSetupAbi",
    "NativeSyntheticContinuationFailureKind",
    "NativeSyntheticContinuationFailureExitBucketCondition",
    "NativeSyntheticContinuationRegister",
    "NativeSyntheticContinuationProvenanceSource",
    "NativeSyntheticSyscallArgumentDescriptor",
    "NativeSyntheticSyscallDescriptor",
    "NativeSyntheticContinuationRegisterSetupDescriptor",
    "NativeSyntheticContinuationRestartContract",
    "NativeSyntheticContinuationStackSetupDescriptor",
    "NativeSyntheticContinuationFailureExitBucket",
    "NativeSyntheticContinuationCompletionDescriptor",
    "NativeSyntheticSyscallContinuationDescriptorRequest",
    "NativeSyntheticSyscallContinuationDescriptorPayload",
    "NativeSyntheticSyscallContinuationDescriptor",
    "NATIVE_SYNTHETIC_SYSCALL_EINTR_EXIT_STATUS",
    "NATIVE_SYNTHETIC_SYSCALL_RESTART_EXIT_STATUS",
    "NATIVE_SYNTHETIC_SYSCALL_UNMODELED_RETURN_EXIT_STATUS",
    "buildNativeSyntheticSyscallContinuationDescriptor",
    "nativeSyntheticEintrErrno",
    "nativeSyntheticRestartLikeErrnos",
    "nativeSyntheticSyscallFailureExitBuckets",
    "nativeSyntheticSyscallRestartContract",
    "nativeSyntheticExitProcessSuffix",
    "nativeSyntheticContinuationBytesHex",
    "nativeSyntheticContinuationBytesSha256",
    "nativeSyntheticContinuationDescriptorSha256",
    "NativeSyntheticPpollCompletionMode",
    "NativeSyntheticPpollSyscallProvenanceSource",
    "NativeSyntheticPpollSyscallArgumentProvenance",
    "NativeSyntheticPpollSyscallCompletionProvenance",
    "NativeSyntheticPpollSyscallRegisterSetupProvenance",
    "NativeSyntheticPpollSyscallStackSetupProvenance",
    "NativeSyntheticPpollSyscallContinuationProvenance",
    "NativeSyntheticPpollSyscallContinuationRequest",
    "NativeSyntheticPpollSyscallContinuation",
    "NativeSyntheticPpollSyscallContinuationResult",
    "NATIVE_SYNTHETIC_PPOLL_SYSCALL_BUILD_ID",
    "NATIVE_SYNTHETIC_PPOLL_SYSCALL_LOGICAL_NAME",
    "NATIVE_SYNTHETIC_PPOLL_SYSCALL_PATH",
    "NATIVE_SYNTHETIC_PPOLL_SYSCALL_BASE",
    "buildNativeSyntheticPpollSyscallContinuation",
    "NativeSyntheticSleepCompletionMode",
    "NativeSyntheticSleepSyscallProvenanceSource",
    "NativeSyntheticSleepSyscallArgumentProvenance",
    "NativeSyntheticSleepSyscallCompletionProvenance",
    "NativeSyntheticSleepSyscallRegisterSetupProvenance",
    "NativeSyntheticSleepSyscallStackSetupProvenance",
    "NativeSyntheticSleepSyscallContinuationProvenance",
    "NativeSyntheticSleepSyscallContinuationRequest",
    "NativeSyntheticSleepSyscallContinuation",
    "NativeSyntheticSleepSyscallContinuationResult",
    "NATIVE_SYNTHETIC_SLEEP_SYSCALL_BUILD_ID",
    "NATIVE_SYNTHETIC_SLEEP_SYSCALL_LOGICAL_NAME",
    "NATIVE_SYNTHETIC_SLEEP_SYSCALL_PATH",
    "NATIVE_SYNTHETIC_SLEEP_SYSCALL_BASE",
    "NATIVE_SYNTHETIC_SLEEP_SYSCALL_EINTR_EXIT_STATUS",
    "NATIVE_SYNTHETIC_SLEEP_SYSCALL_FAILURE_EXIT_STATUS",
    "NATIVE_SYNTHETIC_SLEEP_SYSCALL_RESTART_EXIT_STATUS",
    "NATIVE_SYNTHETIC_SLEEP_SYSCALL_UNMODELED_RETURN_EXIT_STATUS",
    "buildNativeSyntheticSleepSyscallContinuation",
    "NativeTargetLandingModuleProvenance",
    "NativeTargetLandingSectionProvenance",
    "NativeTargetLandingSymbolProvenance",
    "NativeTargetLandingFdeProvenance",
    "NativeTargetLandingDisassemblyProvenance",
    "NativeTargetLandingInstructionBoundary",
    "NativeTargetLandingInstructionBoundaryState",
    "NativeTargetResumeLandingProvenance",
    "NativeTargetResumeLandingInspectionRequest",
    "inspectNativeTargetResumeLanding",
    "nativeTargetResumeLandingRefusals",
    "NativeTargetUnwindRegister",
    "NativeTargetCalleeSavedPolicy",
    "NativeTargetCalleeSavedSlot",
    "NativeTargetUnwindFrameRule",
    "NativeTargetEhFrameTextParseRequest",
    "NativeTargetEhFrameTextParseResult",
    "NativeTargetUnwindMatchRequest",
    "NativeTargetUnwindFrameMatch",
    "NativeTargetUnwindMatchResult",
    "parseNativeTargetEhFrameText",
    "matchNativeTargetUnwindFrame",
    "NativeTargetFrameStateRegister",
    "NativeTargetFrameStateValueSource",
    "NativeSyntheticTargetCallerFrameStatePolicy",
    "NativeTargetFrameRegisterValue",
    "NativeTargetFrameStateRequirement",
    "NativeTargetFrameStateMaterialization",
    "NativeTargetFrameStateMaterializationRequest",
    "NativeTargetFrameStateMaterializationResult",
    "planNativeTargetFrameStateMaterialization",
    "NativeSyntheticTargetCallerFramePolicy",
    "NativeSyntheticTargetCallerFrameSlot",
    "NativeSyntheticTargetCallerFrame",
    "NativeSyntheticTargetCallerFramePlanRequest",
    "NativeSyntheticTargetCallerFramePlanResult",
    "planNativeSyntheticTargetCallerFrame",
    "NativeTargetResumeExecutionAttempt",
    "NativeTargetResumeExecutionAttemptStatus",
    "NativeTargetResumeFaultBoundary",
    "NativeTargetResumeFaultClassification",
    "NativeTargetResumeFaultClassificationOptions",
    "NativeTargetResumeFaultClassificationResult",
    "NativeTargetResumeFaultRegisters",
    "NativeTargetResumeExecutionMode",
    "NativeTargetResumeExecutor",
    "NativeTargetResumeExecutionPlan",
    "NativeTargetResumeExecutionPlanRequest",
    "NativeTargetResumeExecutionPlanResult",
    "classifyNativeTargetResumeExecutionAttempt",
    "planNativeTargetResumeExecution",
    "NativeReturnChainFrameWrite",
    "NativeReturnChainMaterialization",
    "materializeNativeReturnChainFrames",
    "NativeReturnChainFrame",
    "NativeReturnChainPlan",
    "NativeReturnChainPlanFrame",
    "NativeReturnChainPlanRequest",
    "planNativeReturnChain",
    "NativeStackWindowGuardMapping",
    "NativeStackWindowMaterializedWrites",
    "NativeStackWindowWrite",
    "materializeNativeStackWindowWrites",
    "NativeStackFrame",
    "NativeStackPointerRange",
    "NativeStackSlot",
    "NativeStackTranslationRequest",
    "NativeStackTranslationResult",
    "NativeStackWindowMaterializationPlan",
    "NativeStackWindowMaterializationRequest",
    "planNativeStackWindowMaterialization",
    "translateNativeStack",
    "NativeUnwindFrameRule",
    "NativeUnwindStackWord",
    "NativeEhFrameTextParseRequest",
    "NativeEhFrameTextParseResult",
    "NativeUnwindFrameDiscoveryRequest",
    "NativeDiscoveredUnwindFrame",
    "NativeUnwindFrameDiscoveryResult",
    "NativeUnwindMetadataKind",
    "NativeUnwindRegister",
    "discoverNativeUnwindFrames",
    "nativeUnwindReturnAddressSlot",
    "parseNativeEhFrameText",
    "NativeMemoryWord",
    "NATIVE_MACHINE_RESTORE_DESCRIPTOR_FORMAT_VERSION",
    "NATIVE_MACHINE_RESTORE_DESCRIPTOR_KIND",
    "NativeMachineRestoreDescriptor",
    "NativeMachineRestoreDescriptorValidationError",
    "NativeMachineRestorePlan",
    "NativeMachineRestorePlanRequest",
    "buildNativeMachineRestoreDescriptor",
    "parseNativeMachineRestoreDescriptor",
    "planNativeMachineRestore",
    "serializeNativeMachineRestoreDescriptor",
    "validateNativeMachineRestoreDescriptor",
    "NativeMemoryTranslationRequest",
    "NativeMemoryTranslationResult",
    "translateNativeMemory",
    "NativeDebugMemoryField",
    "NativeDebugMemoryObject",
    "NativeDebugAddressTranslation",
    "NativeDebugMemoryPointerClassificationRequest",
    "NativeDebugMemoryPointerClassificationResult",
    "NativeDebugMemoryMetadataSource",
    "NativeDebugMemoryFieldClassification",
    "classifyNativeDebugMemoryPointers",
    "NativeMappingMaterializationAction",
    "NativeMappingMaterializationStep",
    "NativeMappingMaterializationRequest",
    "NativeMappingMaterializationResult",
    "NativePrivateWritableGuardRequest",
    "planNativeMappingMaterialization",
    "NativeInheritedStdioPolicy",
    "NativeResourceTranslationRequest",
    "NativeResourceTranslationResult",
    "NativeTargetFdTableEntryKind",
    "NativeTargetFdTableEntry",
    "NativeTargetFdTablePlanRequest",
    "NativeTargetFdTablePlan",
    "translateNativeResources",
    "planNativeTargetFdTable",
  ],
  "Provision base images": [
    "provision",
    "ProvisionOptions",
    "ProvisionResult",
    "resolveBaseDtb",
    "resolveBaseKernel",
    "resolveBaseRootfs",
    "ensureRootfsImage",
    "EnsureRootfsImageOptions",
    "markRootfsImageClean",
    "rootfsImgCacheDir",
    "resolveMke2fs",
  ],
  "Mount files": [
    "VsockFiles",
    "VsockFilesOptions",
    "WriteFileOptions",
    "buildWriteFileCmd",
    "buildWriteFileCmds",
    "ensureMountDiskImage",
    "ensureMountDiskUpper",
    "markMountDiskImageClean",
    "mountdiskImgCacheDir",
    "resolveMksquashfs",
    "EnsureMountDiskImageOptions",
    "EnsureMountDiskImageResult",
    "EnsureMountDiskUpperOptions",
    "EnsureMountDiskUpperResult",
  ],
  "Share secrets": ["VsockSecrets", "VsockSecretsOptions"],
  "Terminal control": ["VsockWinsize", "VsockWinsizeOptions"],
  "Manage running VMs": [
    "list",
    "registryRoot",
    "RegistryEntry",
    "runGc",
    "GcResult",
    "RunGcOptions",
    "validatePid",
    "PidStatus",
  ],
  "Multiplex sandboxes": [
    "Sandboxes",
    "Supervisor",
    "SandboxEntry",
    "OnOutputListener",
    "SupervisorOptions",
  ],
  "Memory introspection": [
    "MemoryStats",
    "checkForkBackpressure",
    "CheckForkBackpressureOptions",
    "DEFAULT_FREE_MEMORY_THRESHOLD",
    "readHostFreeBytes",
    "readHostTotalBytes",
    "readHostRssBytes",
    "readHostRssBytesMulti",
    "RssTarget",
    "readBalloonStats",
    "BalloonCounters",
    "STATS_FILE_SIZE",
  ],
  Logging: ["ChunkLogEvent", "LogEvent", "OnLog", "PhaseLogEvent"],
  "Initramfs (advanced)": [
    "mkinitramfsBundle",
    "mkinitramfsTinyBundle",
    "mkinitramfsRootfs",
    "mkinitramfsWorkspace",
    "mkinitramfsMinimal",
    "mkinitramfsCli",
    "PackBundleOptions",
    "PackTinyBundleOptions",
    "PackRootfsOptions",
    "PackMinimalOptions",
    "PackWorkspaceOptions",
  ],
  Errors: [
    "MachinenError",
    "BootError",
    "ExecError",
    "SnapshotError",
    "ProvisionError",
    "RegistryError",
    "FilesError",
    "MountError",
    "SecretsError",
    "WinsizeError",
    "SandboxError",
    "CacheError",
    "GvproxyError",
    "MkinitramfsError",
    "ParseError",
    "ErrorCode",
    "MachinenErrorOptions",
    "isMachinenError",
    "formatMachinenError",
  ],
  Internal: ["_internal"],
};

// GitHub-flavored anchor for a markdown header: lowercase, strip
// non-word chars (keep underscores).
function anchor(symbol) {
  return symbol.toLowerCase().replaceAll(/[^a-z0-9_]/g, "");
}

// Strip typedoc-plugin-markdown decorations to get the canonical
// symbol name: function H3s end with `()`, and the markdown writer
// escapes underscores as `\_` so they don't render as italic.
function normalizeHeader(text) {
  return text.replaceAll("\\", "").replace(/\(\)$/, "");
}

const md = readFileSync(API_PATH, "utf8");

const h3s = new Set();
for (const line of md.split("\n")) {
  const m = /^### (.+)$/.exec(line);
  if (m) {
    h3s.add(normalizeHeader(m[1].trim()));
  }
}

// Two-way validation: TOC entries must be real headers, and every
// real header must be in some TOC bucket (or be reported so we can
// add it).
const tocSymbols = new Set(Object.values(TOC).flat());
const tocMissingHeader = [...tocSymbols].filter((s) => !h3s.has(s));
const headerMissingToc = [...h3s].filter((s) => !tocSymbols.has(s));

if (tocMissingHeader.length > 0) {
  console.error(
    `build-api-toc: TOC references symbols that don't appear as H3 in ${API_PATH}:\n  ${tocMissingHeader.join(
      "\n  ",
    )}`,
  );
  process.exit(1);
}
if (headerMissingToc.length > 0) {
  console.error(
    `build-api-toc: H3 symbols in ${API_PATH} that aren't categorised — add them to TOC in scripts/build-api-toc.mjs:\n  ${headerMissingToc.join(
      "\n  ",
    )}`,
  );
  process.exit(1);
}

// Build the TOC block. Markdown details/summary keeps the section
// scannable but compact; readers expand the bucket they need.
const lines = ["## Contents", ""];
for (const [category, symbols] of Object.entries(TOC)) {
  lines.push(`### ${category}`, "");
  for (const s of symbols) {
    lines.push(`- [\`${s}\`](#${anchor(s)})`);
  }
  lines.push("");
}
const tocBlock = lines.join("\n") + "\n";

// Insert after the H1. typedoc emits `# @machinen/runtime` as the
// first non-empty line; we splice the TOC right after the blank line
// that follows.
const out = md.replace(/^(# @machinen\/runtime\n)/, `$1\n${tocBlock}`);
if (out === md) {
  console.error(
    `build-api-toc: couldn't find the H1 in ${API_PATH} — typedoc output shape changed?`,
  );
  process.exit(1);
}

writeFileSync(API_PATH, out);
console.log(`Injected task-grouped TOC into ${API_PATH}`);
